feat (Pages design): Workspace, Program, Auth pages
RareCamp/RareCamp pull request #25
Opened 2021-01-15 11:47 UTC by pipesorter

2021-01-15 11:48 UTC, pipesorter commented on packages/ui/components/AppLayout/AppLayout.tsx
> +      <div data-testid="121" className="w-full min-h-screen">
Would need to remove this @pipesort123TP

2021-01-15 11:49 UTC, pipesorter commented on packages/ui/components/AppLayout/Navbar.tsx
> +    <nav className="bg-white py-4 px-8 h-16 flex items-center justify-between border border-gray-100 hover:border-blue-400">
@pipesort123TP would have to extract out this as a separate class under a module.css

2021-01-15 11:50 UTC, pipesorter commented on packages/ui/components/AppLayout/Navbar.tsx
> +              textColor="purple"
@pipesort123TP can we have this as an array and loop through them?

2021-01-15 11:51 UTC, pipesorter commented on packages/ui/components/Pages/Program/TableRow.tsx
> +    statusClass = 'status-not-started';
@pipesort123TP  why do we have to prefix like this one, can we remove `status-` prefix please?

2021-01-15 11:52 UTC, pipesorter commented on packages/ui/components/Pages/Workspace/Multipleprogram.tsx
> +                        alt=""
@pipesort123TP need to extract out as an hardcoded array, and should be replaced later by backend data

2021-01-15 11:53 UTC, pipesorter commented on packages/ui/pages/workspace/index.tsx
> +                  width={400}
@pipesort123TP need to downcase the name without any spaces any referenced static files.

2021-01-15 11:55 UTC, pipesorter commented on packages/ui/pages/workspace/stepform.tsx
> +  );
@pipesort123TP can we pleas extract out multiple components just like we did for `pages/index.txs` ?

2021-01-17 11:36 UTC, brettstack requested changes
This is excellent work! My only comment is on accessibility

2021-01-17 11:36 UTC, brettstack commented on packages/ui/components/Pages/Program/EditProgramModal.tsx
> +        {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
Please fix or add a code comment why this is disabled

2021-01-20 10:37 UTC, pipesorter commented
@brettstack @sanathkr can you please review and merge this p.r? 🙏

2021-01-20 11:04 UTC, pipesorter commented
@brettstack Oh ya, regarding accessibility, had added the eslint rule through jsx-a11y library, I see some of the rules were disabled, will fix and push now. Will come back to accessibility with `WAVE` tool and fix other issues, for now will do the basic implementation like having the label etc that the library (jsx-a11y) requires.

2021-01-20 14:40 UTC, pipesorter commented
@brettstack done, fixed accessibility-related eslint issues. 🚀

2021-01-20 18:50 UTC, brettstack approved these changes

2021-01-20 18:50 UTC, brettstack commented
Well done! 🤜

2021-01-20 18:51 UTC, merged

2021-03-26 07:29 UTC, brettstack commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/RareCamp/RareCamp/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: